/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ApiSupabaseTenanciesRouteImport } from './routes/api/supabase.tenancies'
import { Route as ApiSupabasePropertiesRouteImport } from './routes/api/supabase.properties'
import { Route as ApiN3ReceiptsRouteImport } from './routes/api/n3.receipts'
import { Route as ApiN3InvoicesRouteImport } from './routes/api/n3.invoices'
import { Route as ApiN3DebitsRouteImport } from './routes/api/n3.debits'
import { Route as ApiN3CreditsRouteImport } from './routes/api/n3.credits'
import { Route as ApiN3ConnectRouteImport } from './routes/api/n3.connect'
import { Route as ApiN3BasicInfoRouteImport } from './routes/api/n3.basic-info'
import { Route as ApiSupabaseTenanciesIdRouteImport } from './routes/api/supabase.tenancies.$id'
import { Route as ApiSupabasePropertiesIdRouteImport } from './routes/api/supabase.properties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabaseTenanciesRoute = ApiSupabaseTenanciesRouteImport.update({
  id: '/api/supabase/tenancies',
  path: '/api/supabase/tenancies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabasePropertiesRoute = ApiSupabasePropertiesRouteImport.update({
  id: '/api/supabase/properties',
  path: '/api/supabase/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3ReceiptsRoute = ApiN3ReceiptsRouteImport.update({
  id: '/api/n3/receipts',
  path: '/api/n3/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3InvoicesRoute = ApiN3InvoicesRouteImport.update({
  id: '/api/n3/invoices',
  path: '/api/n3/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3DebitsRoute = ApiN3DebitsRouteImport.update({
  id: '/api/n3/debits',
  path: '/api/n3/debits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3CreditsRoute = ApiN3CreditsRouteImport.update({
  id: '/api/n3/credits',
  path: '/api/n3/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3ConnectRoute = ApiN3ConnectRouteImport.update({
  id: '/api/n3/connect',
  path: '/api/n3/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN3BasicInfoRoute = ApiN3BasicInfoRouteImport.update({
  id: '/api/n3/basic-info',
  path: '/api/n3/basic-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabaseTenanciesIdRoute = ApiSupabaseTenanciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSupabaseTenanciesRoute,
} as any)
const ApiSupabasePropertiesIdRoute = ApiSupabasePropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSupabasePropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/api/n3/basic-info': typeof ApiN3BasicInfoRoute
  '/api/n3/connect': typeof ApiN3ConnectRoute
  '/api/n3/credits': typeof ApiN3CreditsRoute
  '/api/n3/debits': typeof ApiN3DebitsRoute
  '/api/n3/invoices': typeof ApiN3InvoicesRoute
  '/api/n3/receipts': typeof ApiN3ReceiptsRoute
  '/api/supabase/properties': typeof ApiSupabasePropertiesRouteWithChildren
  '/api/supabase/tenancies': typeof ApiSupabaseTenanciesRouteWithChildren
  '/api/supabase/properties/$id': typeof ApiSupabasePropertiesIdRoute
  '/api/supabase/tenancies/$id': typeof ApiSupabaseTenanciesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/api/n3/basic-info': typeof ApiN3BasicInfoRoute
  '/api/n3/connect': typeof ApiN3ConnectRoute
  '/api/n3/credits': typeof ApiN3CreditsRoute
  '/api/n3/debits': typeof ApiN3DebitsRoute
  '/api/n3/invoices': typeof ApiN3InvoicesRoute
  '/api/n3/receipts': typeof ApiN3ReceiptsRoute
  '/api/supabase/properties': typeof ApiSupabasePropertiesRouteWithChildren
  '/api/supabase/tenancies': typeof ApiSupabaseTenanciesRouteWithChildren
  '/api/supabase/properties/$id': typeof ApiSupabasePropertiesIdRoute
  '/api/supabase/tenancies/$id': typeof ApiSupabaseTenanciesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/api/n3/basic-info': typeof ApiN3BasicInfoRoute
  '/api/n3/connect': typeof ApiN3ConnectRoute
  '/api/n3/credits': typeof ApiN3CreditsRoute
  '/api/n3/debits': typeof ApiN3DebitsRoute
  '/api/n3/invoices': typeof ApiN3InvoicesRoute
  '/api/n3/receipts': typeof ApiN3ReceiptsRoute
  '/api/supabase/properties': typeof ApiSupabasePropertiesRouteWithChildren
  '/api/supabase/tenancies': typeof ApiSupabaseTenanciesRouteWithChildren
  '/api/supabase/properties/$id': typeof ApiSupabasePropertiesIdRoute
  '/api/supabase/tenancies/$id': typeof ApiSupabaseTenanciesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/properties/$id'
    | '/api/n3/basic-info'
    | '/api/n3/connect'
    | '/api/n3/credits'
    | '/api/n3/debits'
    | '/api/n3/invoices'
    | '/api/n3/receipts'
    | '/api/supabase/properties'
    | '/api/supabase/tenancies'
    | '/api/supabase/properties/$id'
    | '/api/supabase/tenancies/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/properties/$id'
    | '/api/n3/basic-info'
    | '/api/n3/connect'
    | '/api/n3/credits'
    | '/api/n3/debits'
    | '/api/n3/invoices'
    | '/api/n3/receipts'
    | '/api/supabase/properties'
    | '/api/supabase/tenancies'
    | '/api/supabase/properties/$id'
    | '/api/supabase/tenancies/$id'
  id:
    | '__root__'
    | '/'
    | '/properties/$id'
    | '/api/n3/basic-info'
    | '/api/n3/connect'
    | '/api/n3/credits'
    | '/api/n3/debits'
    | '/api/n3/invoices'
    | '/api/n3/receipts'
    | '/api/supabase/properties'
    | '/api/supabase/tenancies'
    | '/api/supabase/properties/$id'
    | '/api/supabase/tenancies/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  ApiN3BasicInfoRoute: typeof ApiN3BasicInfoRoute
  ApiN3ConnectRoute: typeof ApiN3ConnectRoute
  ApiN3CreditsRoute: typeof ApiN3CreditsRoute
  ApiN3DebitsRoute: typeof ApiN3DebitsRoute
  ApiN3InvoicesRoute: typeof ApiN3InvoicesRoute
  ApiN3ReceiptsRoute: typeof ApiN3ReceiptsRoute
  ApiSupabasePropertiesRoute: typeof ApiSupabasePropertiesRouteWithChildren
  ApiSupabaseTenanciesRoute: typeof ApiSupabaseTenanciesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase/tenancies': {
      id: '/api/supabase/tenancies'
      path: '/api/supabase/tenancies'
      fullPath: '/api/supabase/tenancies'
      preLoaderRoute: typeof ApiSupabaseTenanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase/properties': {
      id: '/api/supabase/properties'
      path: '/api/supabase/properties'
      fullPath: '/api/supabase/properties'
      preLoaderRoute: typeof ApiSupabasePropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/receipts': {
      id: '/api/n3/receipts'
      path: '/api/n3/receipts'
      fullPath: '/api/n3/receipts'
      preLoaderRoute: typeof ApiN3ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/invoices': {
      id: '/api/n3/invoices'
      path: '/api/n3/invoices'
      fullPath: '/api/n3/invoices'
      preLoaderRoute: typeof ApiN3InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/debits': {
      id: '/api/n3/debits'
      path: '/api/n3/debits'
      fullPath: '/api/n3/debits'
      preLoaderRoute: typeof ApiN3DebitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/credits': {
      id: '/api/n3/credits'
      path: '/api/n3/credits'
      fullPath: '/api/n3/credits'
      preLoaderRoute: typeof ApiN3CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/connect': {
      id: '/api/n3/connect'
      path: '/api/n3/connect'
      fullPath: '/api/n3/connect'
      preLoaderRoute: typeof ApiN3ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n3/basic-info': {
      id: '/api/n3/basic-info'
      path: '/api/n3/basic-info'
      fullPath: '/api/n3/basic-info'
      preLoaderRoute: typeof ApiN3BasicInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase/tenancies/$id': {
      id: '/api/supabase/tenancies/$id'
      path: '/$id'
      fullPath: '/api/supabase/tenancies/$id'
      preLoaderRoute: typeof ApiSupabaseTenanciesIdRouteImport
      parentRoute: typeof ApiSupabaseTenanciesRoute
    }
    '/api/supabase/properties/$id': {
      id: '/api/supabase/properties/$id'
      path: '/$id'
      fullPath: '/api/supabase/properties/$id'
      preLoaderRoute: typeof ApiSupabasePropertiesIdRouteImport
      parentRoute: typeof ApiSupabasePropertiesRoute
    }
  }
}

interface ApiSupabasePropertiesRouteChildren {
  ApiSupabasePropertiesIdRoute: typeof ApiSupabasePropertiesIdRoute
}

const ApiSupabasePropertiesRouteChildren: ApiSupabasePropertiesRouteChildren = {
  ApiSupabasePropertiesIdRoute: ApiSupabasePropertiesIdRoute,
}

const ApiSupabasePropertiesRouteWithChildren =
  ApiSupabasePropertiesRoute._addFileChildren(
    ApiSupabasePropertiesRouteChildren,
  )

interface ApiSupabaseTenanciesRouteChildren {
  ApiSupabaseTenanciesIdRoute: typeof ApiSupabaseTenanciesIdRoute
}

const ApiSupabaseTenanciesRouteChildren: ApiSupabaseTenanciesRouteChildren = {
  ApiSupabaseTenanciesIdRoute: ApiSupabaseTenanciesIdRoute,
}

const ApiSupabaseTenanciesRouteWithChildren =
  ApiSupabaseTenanciesRoute._addFileChildren(ApiSupabaseTenanciesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  ApiN3BasicInfoRoute: ApiN3BasicInfoRoute,
  ApiN3ConnectRoute: ApiN3ConnectRoute,
  ApiN3CreditsRoute: ApiN3CreditsRoute,
  ApiN3DebitsRoute: ApiN3DebitsRoute,
  ApiN3InvoicesRoute: ApiN3InvoicesRoute,
  ApiN3ReceiptsRoute: ApiN3ReceiptsRoute,
  ApiSupabasePropertiesRoute: ApiSupabasePropertiesRouteWithChildren,
  ApiSupabaseTenanciesRoute: ApiSupabaseTenanciesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
